blank_issues_enabled: false
contact_links:
  - name: 💬 IRC
    url: https://web.libera.chat/#youdown
    about: Chat with us via IRC for quick Q/A
  - name: 💬 Matrix
    url: https://matrix.to/#/#youdown:libera.chat
    about: Chat with us via Matrix for quick Q/A
